<?php

namespace App\OpenApi;

use OpenApi\Annotations as OA;

/**
 * @OA\Info(
 *     title="Laravel API",
 *     version="1.0.0",
 *     description="Interactive API documentation generated by Swagger (OpenAPI 3)."
 * )
 *
 * @OA\Server(
 *     url="http://localhost:8000",
 *     description="Local Laravel API server"
 * )
 */
class Swagger
{
    // Container class for global OpenAPI metadata
}


